#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GW2Trader_Android.Resource", IsApplication=true)]

namespace GW2Trader_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::GW2Trader_Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::GW2Trader_Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int placeholder = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int ExecuteSearchButton = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int FilterLayout = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int FilterToggleButton = 2131034119;
			
			// aapt resource value: 0x7f050010
			public const int Icon = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int InvestmentButton = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int ItemName = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Rarity = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int SearchButton = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int SearchFilterText = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int SearchResultListView = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int SearchView = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int SettingsButton = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int Text = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int UpdateDbButton = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int WatchlistButton = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int button1 = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int space1 = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Search = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SearchResultListViewItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int ExpandFilter = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int Hello = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int HideFilter = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int Investments = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Search = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int SearchFilterText = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Settings = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int UpdateDatabase = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int Watchlists = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
