// <auto-generated />
namespace GW2Trader_Windows.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class InvestmentTableadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InvestmentTableadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201503251259089_Investment Table added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
