#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GW2Trader.Android.Resource", IsApplication=true)]

namespace GW2Trader.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::GW2Trader.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::GW2Trader.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int raritiy_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int type_array = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Copper_coin = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Gold_coin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int placeholder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Silver_coin = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int BuyPrice = 2131165194;
			
			// aapt resource value: 0x7f07001d
			public const int Copper = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int CopperIcon = 2131165214;
			
			// aapt resource value: 0x7f070032
			public const int CurrentItemsIndexTextView = 2131165234;
			
			// aapt resource value: 0x7f070018
			public const int DebugButton = 2131165208;
			
			// aapt resource value: 0x7f070000
			public const int DeleteIconsButton = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int Demand = 2131165192;
			
			// aapt resource value: 0x7f070030
			public const int ExecuteSearchButton = 2131165232;
			
			// aapt resource value: 0x7f070019
			public const int Gold = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int GoldIcon = 2131165210;
			
			// aapt resource value: 0x7f070002
			public const int Icon = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int Invest = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int InvestmentButton = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int ItemDetailsFragmentContainer = 2131165201;
			
			// aapt resource value: 0x7f070039
			public const int Itemdetails_Refresh = 2131165241;
			
			// aapt resource value: 0x7f07000d
			public const int LastUpdate = 2131165197;
			
			// aapt resource value: 0x7f070027
			public const int LevelTextView = 2131165223;
			
			// aapt resource value: 0x7f07001f
			public const int ListingQuantity = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int ListingText = 2131165216;
			
			// aapt resource value: 0x7f07000b
			public const int Margin = 2131165195;
			
			// aapt resource value: 0x7f07002b
			public const int MaxLevel = 2131165227;
			
			// aapt resource value: 0x7f07002a
			public const int MaxLevelTextView = 2131165226;
			
			// aapt resource value: 0x7f070029
			public const int MinLevel = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int MinLevelTextView = 2131165224;
			
			// aapt resource value: 0x7f070003
			public const int Name = 2131165187;
			
			// aapt resource value: 0x7f070033
			public const int NextButton = 2131165235;
			
			// aapt resource value: 0x7f070031
			public const int PreviousButton = 2131165233;
			
			// aapt resource value: 0x7f070023
			public const int Price = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int PriceListingListView = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int Quantity = 2131165218;
			
			// aapt resource value: 0x7f070006
			public const int Rarity = 2131165190;
			
			// aapt resource value: 0x7f07002d
			public const int RaritySpinner = 2131165229;
			
			// aapt resource value: 0x7f07000c
			public const int Roi = 2131165196;
			
			// aapt resource value: 0x7f070014
			public const int SearchButton = 2131165204;
			
			// aapt resource value: 0x7f070034
			public const int SearchResultListView = 2131165236;
			
			// aapt resource value: 0x7f070025
			public const int SearchView = 2131165221;
			
			// aapt resource value: 0x7f070009
			public const int SellPrice = 2131165193;
			
			// aapt resource value: 0x7f070017
			public const int SettingsButton = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int Silver = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int SilverIcon = 2131165212;
			
			// aapt resource value: 0x7f070005
			public const int SubType = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int Supply = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int Type = 2131165188;
			
			// aapt resource value: 0x7f07002f
			public const int TypeSpinner = 2131165231;
			
			// aapt resource value: 0x7f070035
			public const int UpdateDbButton = 2131165237;
			
			// aapt resource value: 0x7f07000f
			public const int Watch = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int WatchlistButton = 2131165205;
			
			// aapt resource value: 0x7f070038
			public const int WatchlistCreateButton = 2131165240;
			
			// aapt resource value: 0x7f070037
			public const int WatchlistListView = 2131165239;
			
			// aapt resource value: 0x7f070036
			public const int WatchlistName = 2131165238;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070026
			public const int linearLayout2 = 2131165222;
			
			// aapt resource value: 0x7f07002c
			public const int linearLayout3 = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int linearLayout4 = 2131165230;
			
			// aapt resource value: 0x7f070013
			public const int pts_main = 2131165203;
			
			// aapt resource value: 0x7f070024
			public const int relativeLayout1 = 2131165220;
			
			// aapt resource value: 0x7f070001
			public const int scrollView1 = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int viewPager = 2131165202;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DebugLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemDetailsFragmentContainer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ItemDetailsViewPager = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Money = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PriceListing = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PriceListingListViewItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Search = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SearchResult = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SearchResultListViewItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Settings = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int WatchlistListViewItem = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int WatchlistSelect = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int ItemDetailsMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int AddToNewWatchlist = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Investments = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Search = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Settings = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int UpdateDatabase = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Watchlists = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
