#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GW2Trader.Android.Resource", IsApplication=true)]

namespace GW2Trader.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::GW2Trader.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::GW2Trader.Android.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int raritiy_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int type_array = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Copper_coin = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Gold_coin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int placeholder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Silver_coin = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int BuyPrice = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int Copper = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int CopperIcon = 2131099676;
			
			// aapt resource value: 0x7f060030
			public const int CurrentItemsIndexTextView = 2131099696;
			
			// aapt resource value: 0x7f060016
			public const int DebugButton = 2131099670;
			
			// aapt resource value: 0x7f060000
			public const int DeleteIconsButton = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int Demand = 2131099656;
			
			// aapt resource value: 0x7f06002e
			public const int ExecuteSearchButton = 2131099694;
			
			// aapt resource value: 0x7f060017
			public const int Gold = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int GoldIcon = 2131099672;
			
			// aapt resource value: 0x7f060002
			public const int Icon = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int Invest = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int InvestmentButton = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int ItemDetailsFragmentContainer = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int LastUpdate = 2131099661;
			
			// aapt resource value: 0x7f060025
			public const int LevelTextView = 2131099685;
			
			// aapt resource value: 0x7f06001d
			public const int ListingKind = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int ListingQuantity = 2131099678;
			
			// aapt resource value: 0x7f06000b
			public const int Margin = 2131099659;
			
			// aapt resource value: 0x7f060029
			public const int MaxLevel = 2131099689;
			
			// aapt resource value: 0x7f060028
			public const int MaxLevelTextView = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int MinLevel = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int MinLevelTextView = 2131099686;
			
			// aapt resource value: 0x7f060003
			public const int Name = 2131099651;
			
			// aapt resource value: 0x7f060031
			public const int NextButton = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int PreviousButton = 2131099695;
			
			// aapt resource value: 0x7f060021
			public const int Price = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int PriceListingListView = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int Quantity = 2131099680;
			
			// aapt resource value: 0x7f060006
			public const int Rarity = 2131099654;
			
			// aapt resource value: 0x7f06002b
			public const int RaritySpinner = 2131099691;
			
			// aapt resource value: 0x7f06000c
			public const int Roi = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int SearchButton = 2131099666;
			
			// aapt resource value: 0x7f060032
			public const int SearchResultListView = 2131099698;
			
			// aapt resource value: 0x7f060023
			public const int SearchView = 2131099683;
			
			// aapt resource value: 0x7f060009
			public const int SellPrice = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int SettingsButton = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int Silver = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int SilverIcon = 2131099674;
			
			// aapt resource value: 0x7f060005
			public const int SubType = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int Supply = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int Type = 2131099652;
			
			// aapt resource value: 0x7f06002d
			public const int TypeSpinner = 2131099693;
			
			// aapt resource value: 0x7f060033
			public const int UpdateDbButton = 2131099699;
			
			// aapt resource value: 0x7f06000f
			public const int Watch = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int WatchlistButton = 2131099667;
			
			// aapt resource value: 0x7f060036
			public const int WatchlistCreateButton = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int WatchlistListView = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int WatchlistName = 2131099700;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout1 = 2131099662;
			
			// aapt resource value: 0x7f060024
			public const int linearLayout2 = 2131099684;
			
			// aapt resource value: 0x7f06002a
			public const int linearLayout3 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int linearLayout4 = 2131099692;
			
			// aapt resource value: 0x7f060022
			public const int relativeLayout1 = 2131099682;
			
			// aapt resource value: 0x7f060001
			public const int scrollView1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DebugLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ItemDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemDetailsFragmentContainer = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Money = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PriceListing = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PriceListingListViewItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Search = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SearchResult = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SearchResultListViewItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Settings = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int WatchlistListViewItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int WatchlistSelect = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040007
			public const int AddToNewWatchlist = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Investments = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Search = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Settings = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int UpdateDatabase = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Watchlists = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
